# Generated by Django 2.2.3 on 2019-08-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blog', '0003_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
