# Generated by Django 2.2.3 on 2019-08-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_blog', '0004_remove_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
